title: Mistikids
email: hi@mistikids.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://www.mistikids.com"

collections:
  pages:
    output: true
    permalink: /:name

# page_gen-dirs: true # uncomment, if you prefer to generate named folders
# page_gen:
#   - data: 'merchants'
#     template: 'merchants'
#     name: 'merchant'
#     dir: 'policy-guide'

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: /assets/styles
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - bin
  - config.ru
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/